// ERROR ACTION
export const ERROR_ACTION = "ERROR_ACTION";

// LOGIN ACTIONS
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


// USER ACTIONS
export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USER = "FETCH_USER";
export const UPDATE_USER = "UPDATE_USER";
export const ENABLE_USER = "ENABLE_USER";
export const DISABLE_USER = "DISABLE_USER";



// TRANSFERT ACTIONS
export const SET_DATA_SOURCE = "SET_DATA_SOURCE";
export const SET_DATA_DESTINATAIRE = "SET_CLIENT_DESTINATAIRE";
export const SET_TRANSFERT_INFO = "SET_TRANSFERT_INFO";
export const SET_OPERATION_TYPE = "SET_OPERATION_TYPE";
export const FETCH_TRANSFETS = "FETCH_TRANSFETS";
export const CREATE_TRANSFER = "CREATE_TRANSFER";



// ACCOUNt ACTIONS
export const FETCH_ACCOUNTS_BY_USER = "FETCH_ACCOUNTS_BY_USER";
export const SET_SELECTED_ACCOUNT = "SET_SELECTED_ACCOUNT";
export const FETCH_ALL_ACCOUNTS = "FETCH_ALL_ACCOUNTS";

// AGENCY ACTIONS
export const FETCH_AGENCY_BY_ID = "FETCH_AGENCY_BY_ID";
export const FETCH_AGENCIES = "FETCH_AGENCIES";
export const CREATE_AGENCY = "CREATE_AGENCY";


// CARDS ACTIONS
export const FETCH_CARDS_BY_ACCOUNT_ID = "FETCH_CARDS_BY_ACCOUNT_ID";
export const SET_SELECTED_CARD = "SET_SELECTED_CARD";
export const FETCH_CARDS_NOT_ACCEPTED = "FETCH_CARDS_NOT_ACCEPTED";
export const ACCEPT_CARD = "ACCEPT_CARD";
export const CREATE_CARD = "CREATE_CARD";
export const UPDATE_CARD = "UPDATE_CARD";
export const DETAILS_CARD = "DETAILS_CARD";
export const ENABLE_DISABLE_CARD = "ENABLE_DISABLE_CARD";